export const TODO_GET_SESSION_DATA = 'TODO_GET_SESSION_DATA';  
export const TODO_SET_SESSION_DATA = 'TODO_SET_SESSION_DATA';  
export const TODO_ADD = 'TODO_ADD';  
export const TODO_REMOVE = 'TODO_REMOVE';  